# Generated by Django 3.2.6 on 2022-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='year_of_experience',
            field=models.IntegerField(default=-1),
        ),
    ]
